// Was never used

/*
namespace SantasListGenerator;

public class Weights
{
    public static readonly Dictionary<string, int> Car = new () {
        { "Ford Fiesta", 0 },
        { "Volkswagen Golf", 0 },
        { "Toyota Corolla", 0 },
        { "Honda Civic", 0 },
        { "Chevrolet Cruze", 0 },
        { "BMW 3 Series", 0 },
        { "Audi A4", 0 },
        { "Mercedes-Benz C-Class", 0 },
        { "Hyundai Elantra", 0 },
        { "Nissan Altima", 0 },
        { "Kia Optima", 0 },
        { "Mazda3", 0 },
        { "Subaru Impreza", 0 },
        { "Volkswagen Passat", 0 },
        { "Toyota Camry", 0 },
        { "Honda Accord", 0 },
        { "Chevrolet Malibu", 0 },
        { "Ford Fusion", 0 },
        { "Nissan Maxima", 0 },
        { "Hyundai Sonata", 0 },
        { "Kia Stinger", 0 },
        { "BMW 5 Series", 0 },
        { "Audi A6", 0 },
        { "Mercedes-Benz E-Class", 0 },
        { "Lexus ES", 0 },
        { "Jaguar XF", 0 },
        { "Volvo S60", 0 },
        { "Alfa Romeo Giulia", 0 },
        { "Tesla Model 3", 0 },
        { "Porsche Panamera", 0 },
        { "Chevrolet Impala", 0 },
        { "Chrysler 300", 0 },
        { "Dodge Charger", 0 },
        { "Ford Mustang", 0 },
        { "Chevrolet Camaro", 0 },
        { "Dodge Challenger", 0 },
        { "Toyota Supra", 0 },
        { "Nissan 370Z", 0 },
        { "BMW Z4", 0 },
        { "Audi TT", 0 },
        { "Mercedes-Benz SLK", 0 },
        { "Mazda MX-5 Miata", 0 },
        { "Subaru BRZ", 0 },
        { "Hyundai Veloster", 0 },
        { "Kia Forte", 0 },
        { "Volkswagen Jetta", 0 },
        { "Honda Fit", 0 },
        { "Toyota Yaris", 0 },
        { "Ford Focus", 0 },
        { "Chevrolet Spark", 0 },
    };

    public static readonly Dictionary<string, int> Music = new () {
        { "Pop", 0 },
        { "Rock", 0 },
        { "Hip Hop", 0 },
        { "Jazz", 0 },
        { "Classical", 0 },
        { "Electronic", 0 },
        { "Country", 0 },
        { "R&B", 0 },
        { "Reggae", 0 },
        { "Blues", 0 },
        { "Metal", 0 },
        { "Soul", 0 },
        { "Funk", 0 },
        { "Disco", 0 },
        { "Punk", 0 },
        { "Folk", 0 },
        { "Gospel", 0 },
        { "Latin", 0 },
        { "Ska", 0 },
        { "House", 0 },
        { "Techno", 0 },
        { "Trance", 0 },
        { "Dubstep", 0 },
        { "Ambient", 0 },
        { "Indie", 0 },
        { "Grunge", 0 },
        { "K-Pop", 0 },
        { "J-Pop", 0 },
        { "Opera", 0 },
        { "Swing", 0 },
        { "Bluegrass", 0 },
        { "Afrobeat", 0 },
        { "Salsa", 0 },
        { "Merengue", 0 },
        { "Bossa Nova", 0 },
        { "Flamenco", 0 },
        { "Reggaeton", 0 },
        { "Zouk", 0 },
        { "Calypso", 0 },
        { "Dancehall", 0 },
        { "Electro", 0 },
        { "Synthpop", 0 },
        { "New Wave", 0 },
        { "Post-Punk", 0 },
        { "Shoegaze", 0 },
        { "Emo", 0 },
        { "Hardcore", 0 },
        { "Industrial", 0 },
        { "Trip-Hop", 0 },
        { "World Music", 0 },
    };

    public static readonly Dictionary<string, int> Street = new () {
        { "Aad Gjelles gate", 0 },
        { "Abels gate", 0 },
        { "Absalon Beyers gate", 0 },
        { "Adolph Bergs vei", 0 },
        { "Agnes Mowinckels gate", 0 },
        { "Allégaten", 0 },
        { "Allehelgens gate", 0 },
        { "Amalie Skrams vei", 0 },
        { "Arbeidergaten", 0 },
        { "Armauer Hansens vei", 0 },
        { "Arne Garborgs gate", 0 },
        { "Arnoldus Reimers' gate", 0 },
        { "Asbjørnsens gate", 0 },
        { "Astrups vei", 0 },
        { "Asylplassen", 0 },
        { "Baglergaten", 0 },
        { "Baneveien", 0 },
        { "Bankgaten", 0 },
        { "Bispengsgaten", 0 },
        { "Bjerregårds gate", 0 },
        { "Bjørnsons gate", 0 },
        { "Blaauws vei", 0 },
        { "Bontelabo", 0 },
        { "Bradbenken", 0 },
        { "Bredalsmarken", 0 },
        { "Bredsgården", 0 },
        { "Breistølen", 0 },
        { "Breiviksveien", 0 },
        { "Bryggen", 0 },
        { "Bøhmergaten", 0 },
        { "C. Sundts gate", 0 },
        { "Christian Michelsens gate", 0 },
        { "Christies gate", 0 },
        { "Cort Piil-Smauet", 0 },
        { "Damsgårdsveien", 0 },
        { "Dreggsallmenningen", 0 },
        { "Engen", 0 },
        { "Fabrikkgaten", 0 },
        { "Finnegårdsgaten", 0 },
        { "Fjøsangerveien", 0 },
        { "Fortunen", 0 },
        { "Hans Hauges gate", 0 },
        { "Haugeveien", 0 },
        { "Hollendergaten", 0 },
        { "Jonas Lies vei", 0 },
        { "Kaigaten", 0 },
        { "Kalfarveien", 0 },
        { "Kirkegaten", 0 },
        { "Klosteret", 0 },
        { "Kong Oscars gate", 0 },
    };
}
*/